CREATE TABLE BOX
(ID INTEGER PRIMARY KEY,
 CONTAINED_IN INTEGER
);
CREATE TABLE ITEM
(ID INTEGER PRIMARY KEY,
 CONTAINED_IN INTEGER,
 COLOR VARCHAR(100),
 FOREIGN KEY (CONTAINED_IN) references BOX(ID)
);